name: dotnet

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        dotnet: ['9.0.x']

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release --verbosity normal
